<?php

declare(strict_types=1);

if (isset($this->success) && $this->success && isset($this->message)) {
    echo $this->json($this->message);
} elseif (isset($this->error) && $this->error && isset($this->message)) {
    echo $this->json($this->message);
}
else {
    if (isset($this->form)) {
        $this->form->addSubmit();
        $this->formCollection()->setElementHelper($this->bootstrapFormRow());
        echo $this->bootstrapForm($this->form);
    }
}
