<?php

declare(strict_types=1);

use Laminas\Form\Element\File;
//echo $this->form($form);
$form->prepare();
echo $this->form()->openTag($form);
//foreach($form as $fieldset) :
//var_dump($fieldset);
?>

<?php
foreach ($form as $element) :
    ?>
<div class="form-group">
    <?php
    if ($element instanceof File) {
        echo $this->formFileSessionProgress();
    }
    ?>
    <?= $this->formRow($element) ?>
</div>

    <?php
endforeach;
//endforeach;
echo $this->form()->closeTag($form);
?>
