<?php
if ($this->status === 'success') :
?>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <?= $this->message ?>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<?php
elseif ($this->status === 'error') :
?>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <?= $this->message ?>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<?php
endif;
?>
<?php
if (isset($this->form) && $this->status === 'inprogress') {
    $this->form->addSubmit();
    echo $this->bootstrapForm($this->form);
}