<?php

/*
 * phpcs:ignoreFile
 */

declare(strict_types=1);

use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */

?>
<?= $this->doctype() ?>
<html lang="en" prefix="og: http://ogp.me/ns#">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->config('app_settings')['view']['site_name'] ?? '')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headMeta(); ?>
        <!-- Ie styles -->
        <?=$this->headLink(['rel'  => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/images/favicon.ico'),])
        ->headLink(['rel' => 'preconnect', 'href' => 'https://fonts.gstatic.com'])
        ->appendStylesheet('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap')
        ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css')
        ->appendStylesheet($this->basePath('/theme/inawecups/lib/owlcarousel/assets/owl.carousel.min.css'))
        ->appendStylesheet($this->basePath('/theme/inawecups/css/style.css'))
        ->appendStylesheet($this->basePath('/vendors/mdi/css/materialdesignicons.min.css'))
        ->appendStylesheet($this->basePath('/theme/inawecups/css/inawecups.css'));
        ?>
        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <!-- Topbar Start -->
        <div class="container-fluid">
            <div class="row bg-secondary py-2 px-xl-5">
                <div class="col-lg-6 d-none d-lg-block">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-dark" href="">FAQs</a>
                        <span class="text-muted px-2">|</span>
                        <a class="text-dark" href="">Help</a>
                        <span class="text-muted px-2">|</span>
                        <a class="text-dark" href="">Support</a>
                    </div>
                </div>
                <div class="col-lg-6 text-center text-lg-right">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-dark px-2" href="">
                            <i class="mdi mdi-facebook"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="mdi mdi-twitter"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="mdi mdi-linkedin"></i>
                        </a>
                        <a class="text-dark px-2" href="">
                            <i class="mdi mdi-instagram"></i>
                        </a>
                        <a class="text-dark pl-2" href="">
                            <i class="mdi mdi-youtube"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row align-items-center py-3 px-xl-5">
                <div class="col-lg-3 d-none d-lg-block">
                    <a href="" class="text-decoration-none">
                        <h6 class="m-0 display-5 font-weight-semi-bold">
                            <span class="text-primary font-weight-bold border px-3 mr-1">
                                <?=$this->translate(isset($this->config('app_settings')['view']['site_name']) ? $this->config('app_settings')['view']['site_name'] : '')?>
                            </span>
                        </h6>
                    </a>
                </div>
                <div class="col-lg-6 col-6 text-left">
                    <form action="">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for products">
                            <div class="input-group-append">
                                <span class="input-group-text bg-transparent text-primary">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-3 col-6 text-right">
                    <a href="" class="btn border">
                        <i class="mdi mdi-heart text-primary"></i>
                        <span class="badge">0</span>
                    </a>
                    <a href="<?=$this->url('store/cart', ['action' => 'index'])?>" class="btn border">
                        <i class="mdi mdi-cart text-primary"></i>
                        <span id="cart-badge" class="badge"><span id="cart-count"><?=$this->cart()->getItemCount()?></span></span>
                    </a>
                </div>
            </div>
        </div>
        <!-- Topbar End -->
        <!-- Navbar Start -->
        <div class="container-fluid">
            <div class="row border-top px-xl-5">
                <div class="col-lg-3 d-none d-lg-block">
                    <?= $this->categoryMenu()?>
                </div>
                <div class="col-lg-9">
                    <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                        <a href="" class="text-decoration-none d-block d-lg-none">
                        <h6 class="m-0 display-5 font-weight-semi-bold">
                            <span class="text-primary font-weight-bold border px-3 mr-1">
                                <?=$this->translate(isset($this->config('app_settings')['view']['site_name']) ? $this->config('app_settings')['view']['site_name'] : '')?>
                            </span>
                        </h6>
                        </a>
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                            <div class="navbar-nav mr-auto py-0">
                            <?php
                            // Aurora menu
                                echo $this->navigation('default')->menu()->setMinDepth(0)->setMaxDepth(0)->setUlClass('nav navbar-nav');
                            ?>
                            </div>
                        </div>
                    </nav>
                    <!-- image slider -->
                    <?php
                        if ($this->config('module_settings')['widget']['imageslider']['enable_imageslider'] && isset($this->isHomePage) && isset($this->slider))
                        {
                            echo $this->render($this->slider);
                        }
                    ?>
                    <!-- image slider -->
                </div>
            </div>
        </div>
        <!-- Navbar End -->
        <!-- start action output -->
        <?=$this->content?>
        <!-- end action output -->

        <!-- Subscribe Start -->
        <div class="container-fluid bg-secondary my-5">
            <div class="row justify-content-md-center py-5 px-xl-5">
                <div class="col-md-6 col-12 py-5">
                    <div class="text-center mb-2 pb-2">
                        <h2 class="section-title px-5 mb-3"><span class="bg-secondary px-2">Stay Updated</span></h2>
                        <p>Amet lorem at rebum amet dolores. Elitr lorem dolor sed amet diam labore at justo ipsum eirmod duo labore labore.</p>
                    </div>
                    <form action="">
                        <div class="input-group">
                            <input type="text" class="form-control border-white p-4" placeholder="Email Goes Here">
                            <div class="input-group-append">
                                <button class="btn btn-primary px-4">Subscribe</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- Subscribe End -->

        <!-- Footer Start -->
        <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
            <div class="row px-xl-5 pt-5">
                <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                    <a href="" class="text-decoration-none">
                        <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>Shopper</h1>
                    </a>
                    <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                    <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
                </div>
                <div class="col-lg-8 col-md-12">
                    <div class="row">
                        <div class="col-md-4 mb-5">
                            <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                            <div class="d-flex flex-column justify-content-start">
                                <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                                <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                                <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                                <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                                <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                                <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                            </div>
                        </div>
                        <div class="col-md-4 mb-5">
                            <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                            <div class="d-flex flex-column justify-content-start">
                                <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                                <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                                <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                                <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                                <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                                <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                            </div>
                        </div>
                        <div class="col-md-4 mb-5">
                            <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                            <form action="">
                                <div class="form-group">
                                    <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                        required="required" />
                                </div>
                                <div>
                                    <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row border-top border-light mx-xl-5 py-4">
                <div class="col-md-6 px-xl-0">
                    <p class="mb-md-0 text-center text-md-left text-dark">
                        &copy; <?= date('Y') ?>
                        <a
                        class="text-dark font-weight-semi-bold"
                        href="<?= $this->config('app_settings')['view']['copyright_link'] ?? '#'; ?>"><?= $this->config('app_settings')['view']['copyright_text'] ?? 'Default text'; ?>
                        </a>
                        <br>
                        Website by <a href="https://webinertia.net">Webinertia</a>
                        <br>Theme design by <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a>
                    </p>
                </div>
                <div class="col-md-6 px-xl-0 text-center text-md-right">
                    <img class="img-fluid" src="/theme/inawecups/img/payments.png" alt="">
                </div>
            </div>
        </div>
        <!-- Footer End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-primary back-to-top"><i class="mdi mdi-chevron-up"></i></a>
        <?= $this->inlineScript()
                ->offsetSetFile(-10,$this->basePath('/theme/inawecups/js/jquery-3.5.1.min.js'))
                ->offsetSetFile(-9, $this->basePath('/theme/inawecups/js/bootstrap.bundle.js'))
                //->appendFile($this->basePath('/theme/inawecups/lib/easing/easing.min.js'))
                ->offsetSetFile(-8, $this->basePath('/theme/inawecups/lib/owlcarousel/owl.carousel.js'))
                ->offsetSetFile(-7, $this->basePath('/theme/inawecups/js/main.js'));
            ?>
    <?php
    $enablePayment = $this->config()['module_settings']['payment']['enabled'];
    if ($enablePayment && $this->integrationType === 'hosted_fields') : ?>
        <script type="text/javascript">
            var form = $('form');
            braintree.client.create({
                authorization: "<?=$this->clientToken?>",
            },
            function(err, clientInstance) {
                    if (err) {
                        console.error(err);
                        return;
                    }
                    braintree.dataCollector.create({
                        client: clientInstance
                    },
                    function (err, dataCollectorInstance) {
                        if (err) {
                            // Handle error in creation of data collector
                            return;
                        }
                        // At this point, you should access the dataCollectorInstance.deviceData value and provide it
                        // to your server, e.g. by injecting it into your form as a hidden input.
                        var deviceData = dataCollectorInstance.deviceData;
                        $('#deviceData').val(deviceData);
                    });
                    braintree.hostedFields.create({
                        client: clientInstance,
                        styles: {
                            input: {
                                // change input styles to match bootstrap styles
                                'font-size': '1rem',
                                color: '#495057'
                            }
                        },
                        fields: {
                            cardholderName: {
                                selector: '#cc-name',
                                placeholder: 'Name as it appears on your card'
                            },
                            number: {
                                selector: '#cc-number',
                                placeholder: '4111 1111 1111 1111'
                            },
                            cvv: {
                                selector: '#cc-cvv',
                                placeholder: '123'
                            },
                            expirationDate: {
                                selector: '#cc-expiration',
                                placeholder: 'MM / YY'
                            }
                        }
                    }, function(err, hostedFieldsInstance) {
                    if (err) {
                        console.error(err);
                        return;
                    }
                    function createInputChangeEventListener(element) {
                        return function () {
                            validateInput(element);
                        }
                    }
                    function setValidityClasses(element, validity) {
                        if (validity) {
                            element.removeClass('is-invalid');
                            element.addClass('is-valid');
                        } else {
                            element.addClass('is-invalid');
                            element.removeClass('is-valid');
                        }
                    };

                    function validateInput(element) {
                        // very basic validation, if the
                        // fields are empty, mark them
                        // as invalid, if not, mark them
                        // as valid
                        if (!element.val().trim()) {
                            setValidityClasses(element, false);
                            return false;
                        }
                        setValidityClasses(element, true);
                            return true;
                    };

                    function validateEmail () {
                        var baseValidity = validateInput(email);
                        if (!baseValidity) {
                            return false;
                        }
                        if (email.val().indexOf('@') === -1) {
                            setValidityClasses(email, false);
                            return false;
                        }
                        setValidityClasses(email, true);
                        return true;
                    };
                    var ccName = $('#cc-name');
                    var email = $('#email');
                    ccName.on('change', function () {
                        validateInput(ccName);
                    });
                    email.on('change', validateEmail);
                    hostedFieldsInstance.on('validityChange', function(event) {
                        var field = event.fields[event.emittedBy];
                        // Remove any previously applied error or warning classes
                        $(field.container).removeClass('is-valid');
                        $(field.container).removeClass('is-invalid');

                        if (field.isValid) {
                            $(field.container).addClass('is-valid');
                        } else if (field.isPotentiallyValid) {
                            // skip adding classes if the field is
                            // not valid, but is potentially valid
                        } else {
                            $(field.container).addClass('is-invalid');
                        }
                    });
                    hostedFieldsInstance.on('cardTypeChange', function(event) {
                        var cardBrand = $('#card-brand');
                        var cvvLabel = $('[for="cc-cvv"]');
                        if (event.cards.length === 1) {
                            var card = event.cards[0];
                            // change pay button to specify the type of card
                            // being used
                            cardBrand.text(card.niceType);
                            // update the security code label
                            cvvLabel.text(card.code.name);
                        } else {
                            // reset to defaults
                            cardBrand.text('Card');
                            cvvLabel.text('CVV');
                        }
                    });
                    form.submit(function(event) {
                        event.preventDefault();
                        var formIsInvalid = false;
                        var state = hostedFieldsInstance.getState();
                        // perform validations on the non-Hosted Fields
                        // inputs
                        if (! validateEmail()) {
                            formIsInvalid = true;
                        }
                        // Loop through the Hosted Fields and check
                        // for validity, apply the is-invalid class
                        // to the field container if invalid
                        Object.keys(state.fields).forEach(function(field) {
                            // if (! state.fields[field].isValid) {
                            //     $(state.fields[field].container).addClass('is-invalid');
                            //     formIsInvalid = true;
                            // }
                        });
                        if (formIsInvalid) {
                            // skip tokenization request if any fields are invalid
                            //return;
                        }
                        hostedFieldsInstance.tokenize(function(err, payload) {
                            if (err) {
                                console.error(err);
                                return;
                            }
                            // This is where you would submit payload.nonce to your server
                            // $('.toast').toast('show');
                            // you can either send the form values with the payment
                            // method nonce via an ajax request to your server,
                            // or add the payment method nonce to a hidden inpiut
                            // on your form and submit the form programatically
                            $('#payment-method-nonce').val(payload.nonce);
                            form.submit();
                        });
                    });
                });
            });
        </script>
    <?php endif; ?>
    <?php if ($enablePayment && $this->integrationType === 'drop_in') : ?>
        <script type="text/javascript">
            const form     = document.getElementById('payment-form');
            const shipping = document.getElementById('shipping');
            braintree.dropin.create({
                authorization: '<?=$this->clientToken?>',
                container: '#dropin-container',
                dataCollector: true,
                card: {
                    // include the card holder name
                    cardholderName: {
                        required: true
                    }
                }
            }, (error, dropinInstance) => {
                if (error) console.error(error);

                form.addEventListener('submit', event => {
                    event.preventDefault();
                    dropinInstance.requestPaymentMethod((error, payload) => {
                    if (error) console.error(error);

                    // Step four: when the user is ready to complete their
                    //   transaction, use the dropinInstance to get a payment
                    //   method nonce for the user's selected payment method, then add
                    //   it a the hidden field before submitting the complete form to
                    //   a server-side integration
                    document.getElementById('nonce').value = payload.nonce;
                    form.submit();
                    });
                });
            });
        </script>
    <?php endif; ?>
    </body>
</html>