<?php

/*
 * phpcs:ignoreFile
 */

declare(strict_types=1);

use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */

?>
<?= $this->doctype() ?>
<html lang="en" prefix="og: http://ogp.me/ns#">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->config('app_settings')['view']['site_name'] ?? '')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headMeta(); ?>
        <!-- Ie styles -->
        <?= $this->headLink(
            [
                'rel'  => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath('/images/favicon.ico'),
            ]
        )->appendStylesheet($this->basePath('/theme/inawecups/css/style.css'))
        //->appendStylesheet($this->basePath('/theme/inawecups/css/inawecups.css'))
        ->appendStylesheet($this->basePath('/theme/inawecups/lib/owlcarousel/assets/owl.carousel.min.css'))
        ->appendStylesheet($this->basePath('vendors/mdi/css/materialdesignicons.min.css'));
        ?>
        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-xl-5">

            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-dark pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <h5 class="m-0 display-5 font-weight-semi-bold"><a href="<?= $this->url('home') ?>" class="text-decoration-none"><span class="text-primary font-weight-bold border px-3 mr-1"><?= $this->translate($this->config('app_settings')['view']['site_name'] ?? 'Home'); ?></span></a></h5>
            </div>
            <div class="col-lg-6 col-6 text-left">
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for products">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                <a href="" class="btn border">
                    <i class="fas fa-heart text-primary"></i>
                    <span class="badge">0</span>
                </a>
                <a href="" class="btn border">
                    <i class="fas fa-shopping-cart text-primary"></i>
                    <span class="badge">0</span>
                </a>
            </div>
        </div>
    </div>
    <!-- Topbar End -->

    <!-- Navbar Start -->
    <div class="container-fluid mb-5">
        <div class="row border-top px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Categories</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0" id="navbar-vertical">
                    <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link" data-toggle="dropdown">Dresses <i class="fa fa-angle-down float-right mt-1"></i></a>
                            <div class="dropdown-menu position-absolute bg-secondary border-0 rounded-0 w-100 m-0">
                                <a href="" class="dropdown-item">Men's Dresses</a>
                                <a href="" class="dropdown-item">Women's Dresses</a>
                                <a href="" class="dropdown-item">Baby's Dresses</a>
                            </div>
                        </div>
                        <a href="" class="nav-item nav-link">Shirts</a>
                        <a href="" class="nav-item nav-link">Jeans</a>
                        <a href="" class="nav-item nav-link">Swimwear</a>
                        <a href="" class="nav-item nav-link">Sleepwear</a>
                        <a href="" class="nav-item nav-link">Sportswear</a>
                        <a href="" class="nav-item nav-link">Jumpsuits</a>
                        <a href="" class="nav-item nav-link">Blazers</a>
                        <a href="" class="nav-item nav-link">Jackets</a>
                        <a href="" class="nav-item nav-link">Shoes</a>
                    </div>
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            <a href="index.html" class="nav-item nav-link active">Home</a>
                            <a href="shop.html" class="nav-item nav-link">Shop</a>
                            <a href="detail.html" class="nav-item nav-link">Shop Detail</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
                                <div class="dropdown-menu rounded-0 m-0">
                                    <a href="cart.html" class="dropdown-item">Shopping Cart</a>
                                    <a href="checkout.html" class="dropdown-item">Checkout</a>
                                </div>
                            </div>
                            <a href="contact.html" class="nav-item nav-link">Contact</a>
                        </div>
                        <div class="navbar-nav ml-auto py-0">
                            <?php if (! $this->identity()->hasIdentity()) { ?>
                            <a href="user/account/login" class="nav-item nav-link">Login</a>
                            <a href="user/register" class="nav-item nav-link">Register</a>
                            <?php } else { ?>
                            <a href="user/account/logout" class="nav-item nav-link">Logout</a>
                           <?php  } ?>

                        </div>
                    </div>
                </nav>
                <!-- image slider -->
                <?php
                    if ($this->config('module_settings')['widget']['imageslider']['enable_imageslider'] && isset($this->slider))
                    {
                        echo $this->render($this->slider);
                    }
                ?>
                <!-- image slider -->
            </div>
        </div>
    </div>
    <!-- Navbar End -->
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                     <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <?php
                        echo $this->navigation('default')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav');
                    ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                        &times;
                    </button>
                    <ul><li>')
                ->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>');
                $plugin = $this->flashMessenger()->getPluginFlashMessenger();
                if ($plugin->hasCurrentErrorMessages()) {
                    echo $flash->render('error', ['alert', 'alert-dismissible fade show', 'alert-danger']);
                }
                if ($plugin->hasCurrentInfoMessages()) {
                    echo $flash->render('info', ['alert', 'alert-dismissible fade show', 'alert-info']);
                }
                if ($plugin->hasCurrentSuccessMessages()) {
                    echo $flash->render('success', ['alert', 'alert-dismissible fade show', 'alert-success']);
                }
                ?>
                <?php
                if ((int) $this->config('app_settings')['view']['show_breadcrumbs']) :
                    echo $this->navigation()->breadcrumbs()->setMinDepth(0)->render();
                endif;
                ?>
            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="<?= $this->config('app_settings')['view']['copyright_link'] ?? '#'; ?>">
                    <?= $this->config('app_settings')['view']['copyright_text'] ?? 'Default text'; ?></a>
                    |
                    <?= $this->config('app_settings')['view']['footer_text'] ?? 'Default Text'; ?>
                </p>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->appendFile($this->basePath('/js/jquery-3.5.1.min.js'))
            ->appendFile($this->basePath('/js/bootstrap.bundle.js'))
            ->appendFile($this->basePath('/theme/inawecups/lib/easing/easing.min.js'))
            ->appendFile($this->basePath('/js/owl-carousel.js'))
            ->appendFile($this->basePath('/js/tinymce/tinymce.min.js'))
            ->appendFile($this->basePath('/js/tinymce/jquery.tinymce.min.js'))
            ->appendFile($this->basePath('/js/cms.js'));
        ?>
    </body>
</html>
