<?php if($this->pageCount): ?>
<nav aria-label="Page navigation">
    <ul id="pagination-control" class="pagination justify-content-center mb-3">
    <?php if (! isset($this->previous)): ?>
            <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
    <?php else: ?>
            <li class="page-item">
                <a class="page-link" href="<?=$this->url($this->route, ['action' => 'index', 'category' => $this->category, 'product' => 'all'], ['query' => ['page' => $this->previous]])?>" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
    <?php endif; ?>

    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li class="page-item">
                <a class="page-link" href="<?=$this->url(
                    $this->route,
                    ['action' => 'index', 'category' => $this->category, 'product' => 'all'],
                    [
                        'query' => [
                            'page' => $page,
                        ],
                    ])?>"><?=$page?></a>
            </li>
        <?php else: ?>
            <li class="page-item active">
                <a class="page-link" href="<?=$this->url(
                    $this->route,
                    ['action' => 'index', 'category' => $this->category, 'product' => 'all'],
                    [
                        'query' => [
                            'page' => $this->current,
                        ],
                    ])?>"><?=$this->current?></a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
    <?php if (isset($this->next)): ?>
        <li class="page-item">
            <a class="page-link" href="<?=$this->url($this->route, ['action' => 'index', 'category' => $this->category, 'product' => 'all'], ['query' => ['page' => $this->next]])?>" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    <?php else: ?>
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    <?php endif; ?>
    </ul>
</nav>
<?php endif; ?>
<?php
//$this->url('product.search', ['action' => 'index', 'category' => $this->category, 'product' => 'all'], ['query' => ['page' => 1]]);
?>