<?php
// at this point this file is not used since there is a recdirect from the controller back to the list action
?>
    <?php
    if($this->acl()->isAllowed($this->user, $deactivatedUser, 'delete') && $deactivatedUser->id !== '1'):
    ?>
        <a class="mdi mdi-delete-forever text-danger align-middle" data-toggle="tooltip" title="Delete User" href="<?= $this->url('user/account/delete', ['userName' => $deactivatedUser->userName]); ?>"></a>
    <?php
    endif;
    ?>
    <?php
    if($this->acl()->isAllowed($this->user, $deactivatedUser, 'edit') || $this->acl()->isAllowed($this->user, 'account', 'edit')): ?>
        <a class="mdi mdi-account-edit text-success align-middle" data-toggle="tooltip" title="Edit User" href="<?=$this->url('user/account/edit', ['userName' => $deactivatedUser->userName]); ?>"></a>
    <?php
    endif; ?>
    <span> | </span>
    <?php
    if ($deactivatedUser->active) { ?>
        <span class="mdi mdi-check-circle text-success align-middle" data-toggle="tooltip" title="Active Account"></span>
    <?php
    } else {
        if ($this->acl()->isAllowed($this->user, 'account', 'edit')) { ?>
            <a class="mdi mdi-check-circle text-danger align-middle manage-user"
            data-toggle="tooltip" title="Activate Account?"
            href="<?=$this->url('user/account/staff-activate', ['userName' => $deactivatedUser->userName]); ?>"></a>
    <?php
        }
    }
    ?>
