<?php

/*
 * phpcs:ignoreFile
 */

 declare(strict_types=1);

 use Laminas\Form\View\HelperTrait;
 use Laminas\View\Renderer\PhpRenderer;

 /** @var PhpRenderer|HelperTrait $this */
if (isset($this->model)):
?>
<div id="categoryImageManager">
    <?=$this->partialLoop('/partials/image-listing.phtml', $this->model)?>
</div>
<?php
endif;
?>
<script>
require([
    "aurora/Aurora",
    "dojo/_base/array",
    "dojo/query",
    "dojo/_base/lang",
    "dojo/dom",
    "dojo/dom-class",
    "dojo/dom-attr",
    "dojo/dom-form",
    "dojo/topic",
    "dojo/request",
    "dojo/on",
    "dijit/registry",
    "dojox/layout/ContentPane",
    "dojox/form/Manager",
    "dijit/form/Button",
    "dojo/domReady!"
], function(Aurora, arrayUtil, query, lang, dom, domClass, domAttr, domForm, topic, request, on, registry, ContentPane, fm, Button) {


});
</script>