<?php

/*
 * phpcs:ignoreFile
 */

declare(strict_types=1);

use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>
<div class="row">
    <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                            <h5 class="mb-0">Create Category</h5>
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="icon icon-box-success">
                        <a class="product-manager-control mdi mdi-arrow-top-right icon-item" href="<?=$this->url('admin.store/manage/categories', ['action' => 'create'])?>"></a>
                        </div>
                    </div>
                </div>
                <h6 class="text-muted font-weight-normal">loading index action</h6>
            </div>
        </div>
    </div>
</div>