<?php

declare(strict_types=1);

use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 */
?>
<div class="jumbotron">
    <div class="card-deck">
        <div class="card">
            <div class="card-body">
            <?php
            if (isset($form) && $this->appSettings['email']['enable_contact_form']) :
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->bootstrapForm($form);
                echo $this->form()->closeTag($form);
            endif;
            ?>
            </div>
        </div>
    </div>
</div>
