<?php

declare(strict_types=1);

use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use Webinertia\Utils\Debug;

/**
 * @var PhpRenderer|HelperTrait $this
 */
$view = $this->config('app_settings')['view'];
?>
<?= $this->doctype() ?>
<html class="h-100" data-bs-theme="light" lang="en" prefix="og: http://ogp.me/ns#">
    <head>
        <?= $this->headTitle($view['site_name'] ?? '')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php
        $this->headMeta()
        ->setCharSet('UTF-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headMeta(); ?>
        <!-- Ie styles -->
        <?= $this->headLink(
            [
                'rel'  => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/images/favicon.ico',
            ]
        )->appendStylesheet($this->basePath('theme/default/css/bootstrap.min.css'))
        ->appendStylesheet($this->basePath('/theme/default/css/style.css'))
        ->appendStylesheet($this->basePath('vendors/mdi/css/materialdesignicons.min.css')); // this may be removed
        ?>
        <?php
            $this->inlineScript()
            ->appendFile($this->basePath('theme/default/js/jquery-3.6.4.min.js'))
            ->appendFile('https://unpkg.com/@popperjs/core@2')
            ->appendFile($this->basePath('theme/default/js/bootstrap.min.js'))
            ->appendFile($this->basePath('theme/default/js/pubsub.js'))
            ->appendFile($this->basePath('theme/default/js/app.js'));
        ?>
        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body class="d-flex flex-column h-100">
        <nav class="navbar navbar-expand-md">
            <div class="container rounded bg-body-tertiary shadow-sm">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                     <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>"><?= $this->translate($view['site_name'] ?? 'Home'); ?></a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <?php
                        echo $this->navigation('default')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav');
                    ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                        &times;
                    </button>
                    <ul><li>')
                ->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>');
                $plugin = $this->flashMessenger()->getPluginFlashMessenger();
                if ($plugin->hasCurrentErrorMessages()) {
                    echo $flash->render('error', ['alert', 'alert-dismissible fade show', 'alert-danger']);
                }
                if ($plugin->hasCurrentInfoMessages()) {
                    echo $flash->render('info', ['alert', 'alert-dismissible fade show', 'alert-info']);
                }
                if ($plugin->hasCurrentSuccessMessages()) {
                    echo $flash->render('success', ['alert', 'alert-dismissible fade show', 'alert-success']);
                }
                ?>
                <?php
                if ((int) $this->config('app_settings')['view']['show_breadcrumbs']) :
                    echo $this->navigation()->breadcrumbs()->setMinDepth(0)->render();
                endif;
                ?>
            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="<?= $view['copyright_link'] ?? '#'; ?>">
                    <?= $view['copyright_text'] ?? 'Default text'; ?></a>
                    |
                    <?= $view['footer_text'] ?? 'Default Text'; ?>
                </p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
