<?php

declare(strict_types=1);

use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 */
?>
<?= $this->doctype() ?>
<html lang="en" prefix="og: http://ogp.me/ns#">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->appSettings->view->site_name ?? '')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
        ->prependName('keywords', $this->appSettings->seo->key_words ?? '')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')

        ?>
        <!-- Ie styles -->
        <?= $this->headLink(
                            [
                                'rel'  => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico',
                            ]
            )->prependStylesheet($this->basePath('css/style.css'))
             ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                     <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>"><?= $this->translate($this->appSettings->view->site_name ?? 'Home'); ?></a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <?php
                    $this->navigation()->menu()->setUlClass('navbar-nav');
                    echo $this->navigation('Laminas\Navigation\Default')->menu();
                    ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                        &times;
                    </button>
                    <ul><li>')
                ->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>');
                $plugin = $this->flashMessenger()->getPluginFlashMessenger();
                if ($plugin->hasCurrentErrorMessages()) {
                    echo $flash->render('error', ['alert', 'alert-dismissible', 'alert-danger']);
                }
                if ($plugin->hasCurrentInfoMessages()) {
                    echo $flash->render('info', ['alert', 'alert-dismissible', 'alert-info']);
                }
                if ($plugin->hasCurrentSuccessMessages()) {
                    echo $flash->render('success', ['alert', 'alert-dismissible', 'alert-success']);
                }
                ?>
            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="<?= $this->appSettings->view->copyright_link ?? '#'; ?>">
                    <?= $this->appSettings->view->copyright_text ?? 'Default text'; ?></a>
                    |
                    <?= $this->appSettings->view->footer_text ?? 'Default Text'; ?>
                </p>
                <?php
                // if(!$this->auth->hasIdentity())
                //     echo $this->renderChildModel('inlineLogin');
                ?>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
