<?php

declare(strict_types=1);

use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer|HelperTrait $this
 */
?>
<?= $this->doctype() ?>
<html lang="en" prefix="og: http://ogp.me/ns#">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->appSettings['view']['site_name'] ?? '')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headMeta(); ?>
        <!-- Ie styles -->
        <?= $this->headLink(
            [
                'rel'  => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/images/favicon.ico',
            ]
        )->appendStylesheet($this->basePath('css/bootstrap.min.css'))
             ->appendStylesheet($this->basePath('css/style.css'))
             ->appendStylesheet($this->basePath('vendors/mdi/css/materialdesignicons.min.css'));
        ?>
        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                     <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>"><?= $this->translate($this->appSettings['view']['site_name'] ?? 'Home'); ?></a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <?php
                        echo $this->navigation('default')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav');
                    ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                        &times;
                    </button>
                    <ul><li>')
                ->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>');
                $plugin = $this->flashMessenger()->getPluginFlashMessenger();
                if ($plugin->hasCurrentErrorMessages()) {
                    echo $flash->render('error', ['alert', 'alert-dismissible fade show', 'alert-danger']);
                }
                if ($plugin->hasCurrentInfoMessages()) {
                    echo $flash->render('info', ['alert', 'alert-dismissible fade show', 'alert-info']);
                }
                if ($plugin->hasCurrentSuccessMessages()) {
                    echo $flash->render('success', ['alert', 'alert-dismissible fade show', 'alert-success']);
                }
                ?>
                <?php
                if ((int) $this->config('app_settings')['view']['show_breadcrumbs']) :
                    echo $this->navigation()->breadcrumbs()->setMinDepth(0)->render();
                endif;
                ?>
            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy; <?= date('Y') ?>
                    <a href="<?= $this->config('app_settings')['view']['copyright_link'] ?? '#'; ?>">
                    <?= $this->config('app_settings')['view']['copyright_text'] ?? 'Default text'; ?></a>
                    |
                    <?= $this->config('app_settings')['view']['footer_text'] ?? 'Default Text'; ?>
                </p>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->appendFile($this->basePath('js/jquery-3.5.1.min.js'))
            ->appendFile($this->basePath('js/bootstrap.bundle.js'))
            ->appendFile($this->basePath('/js/tinymce/tinymce.min.js'))
            ->appendFile($this->basePath('/js/tinymce/jquery.tinymce.min.js'))
            ->appendFile($this->basePath('/js/cms.js'));
        ?>
    </body>
</html>
