<?php

declare(strict_types=1);

/**
 * @var $this \Laminas\View\Renderer\PhpRenderer|\Laminas\Form\View\HelperTrait
 */
//$this->
$this->headLink()->prependStylesheet($this->basePath('css/aurora.css'));
$title = 'Edit User';
$this->headTitle($title);
?>
<h3><?= $this->escapeHtml($title) ?></h3>
<p><?= $this->translate('edit_user_notice'); ?></p>
<?php

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email');
$email->setAttribute('maxlength', '100');
?>
<?php
//var_dump($this->acl);
if ($acl->isAllowed($this->user, $this->user, 'admin.user')) :
    $role = $form->get('role');
    $role->setAttribute('class', 'form-control');
endif;
$password = $form->get('password');
$password->setAttribute('class', 'form-control');

$conf_password = $form->get('conf_password');
$conf_password->setAttribute('class', 'form-control');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', [
    'action'   => 'edit',
    'userName' => $userName,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
</div>
<?php
//var_dump($this->acl);
if ($acl->isAllowed($this->user, $this->user, 'admin.user')) :
    ?>
<div class="form-group">
    <?= $this->formLabel($role); ?>
    <?= $this->formElement($role); ?>
    <?= $this->formElementErrors()->render($role, ['class' => 'help-block']) ?>
</div>
    <?php
endif;
?>
<div class="form-group">
    <?= $this->formLabel($password); ?>
    <?= $this->formElement($password); ?>
    <?= $this->formElementErrors()->render($password); ?>
</div>
<div class="form-group">
    <?= $this->formLabel($conf_password); ?>
    <?= $this->formElement($conf_password); ?>
    <?= $this->formElementErrors()->render($conf_password); ?>
</div>
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
