<?php

declare(strict_types=1);

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">A Content Management System</h1>
    <p>Loading from the modules view folder</br>
        Congratulations! You have successfully installed <a href="https://github.com/Tyrsson/aurora-2.0/wiki" target="_blank">ACMS</a>.
    </p>
    <hr class="my-4">
    <a class="btn btn-primary btn-lg" href="https://github.com/Tyrsson/aurora-2.0" target="_blank">
        Check Aurora on GitHub &raquo;
    </a>
</div>
<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Follow Development</h2>
        <div class="card-body">
            <p>
                This project is being actively developed by <a href="https://github.com/Tyrsson">Tyrsson</a> .
            </p>
            <a class="btn btn-primary" href="#" target="_blank">Project Portal &raquo;</a>
        </div>
    </div>
    <div class="card">
        <h2 class="card-header">Placeholder Heading</h2>
        <div class="card-body">
            <p>
                This application is not ready for use.
            </p>
            <a class="btn btn-primary" href="#" target="_blank">
                Modules &raquo;
            </a>
        </div>
    </div>
    <div class="card">
        <h2 class="card-header">Help &amp; Support</h2>
        <div class="card-body">
            <p>
                This is placeholder text
            </p>
        </div>
    </div>
</div>
