<?php

declare(strict_types=1);

use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */

$title = 'Profile';
$this->headTitle($title);
// phpcs
?>
<div class="jumbotron">
    <div class="container">
        <div class="main-body">
            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div id="member-details" class="d-flex flex-column align-items-center text-center">
                                <img src="/modules/user/profile/profileImages/<?=$this->data->profileImage;?>" alt="<?=$this->data->getGroupName()?>" class="rounded-circle" width="150">
                                <div class="mt-3">
                                    <h4>
                                        <?php
                                        if (isset($this->data->firstName) && isset($this->data->lastName)) {
                                            echo $this->data->firstName . ' ' . $this->data->lastName;
                                        } else {
                                            echo $this->data->userName;
                                        }
                                        ?>
                                    </h4>
                                    <p class="text-primary mb-1">
                                        <?=$this->translate($this->data->getGroupName(), 'default');?>
                                    </p>
                                    <?php
                                    if (isset($this->data->jobTitle)) :
                                        ?>
                                    <p class="text-primary mb-1">
                                        <?=$this->data->jobTitle;?>
                                    </p>
                                        <?php
                                    endif;
                                    ?>
                                    <p class="text-primary mb-1"></p>
                                    <p class="text-muted font-size-sm">
                                        <?php
                                        if (isset($this->data->city) && isset($this->data->state)) {
                                            echo $this->data->city . ', ' . $this->data->state;
                                        }
                                        ?>
                                    </p>
                                    <button class="btn btn-sm btn-info">Follow</button>
                                <?php
                                if ($this->acl()->isAllowed($this->identity()->getIdentity(), 'personal-message', 'send')) :
                                    ?>
                                    <button class="btn btn-sm btn-outline-primary">Message</button>
                                    <?php
                                endif;
                                ?>
                                <?php
                                if ($this->acl()->isAllowed($this->identity()->getIdentity(), $data, 'edit')) :
                                    ?>
                                    <button
                                        class="btn btn-sm btn-info"
                                        role="button"
                                        data-section="member-details"
                                        data-toggle="modal"
                                        data-target="#profileModal"
                                        data-href="<?=$this->url('user/manage-profile', ['action' => 'member-details', 'userName' => $data->userName]) ?>">Edit</button>
                                    <?php
                                endif;
                                ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card mt-3">
                        <ul id="social-media" class="list-group list-group-flush text-primary">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
                                <span class="text-primary"><a data-target="href" href="<?=isset($this->data->webUrl) ? $this->data->webUrl : '#';?>">Visit Site</a></span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
                                <span class="text-primary"><a href="<?=isset($this->data->github) ? $this->data->github : '#';?>">View Github</a></span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
                                <span class="text-primary"><a href="<?=isset($this->data->twitter) ? $this->data->twitter : '#';?>"><?=isset($this->data->twitter) ? $this->data->twitter : 'Not Provided';?></a></span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                                <span class="text-primary"><a href="<?=isset($this->data->instagram) ? $this->data->instagram : '#';?>">View Instagram</a></span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
                                <span class="text-primary"><a href="<?=isset($this->data->facebook) ? $this->data->facebook : '#';?>">View Facebook</a></span>
                            </li>
                        </ul>
                        <?php
                        if ($this->acl()->isAllowed($this->identity()->getIdentity(), $data, 'edit')) :
                            ?>
                            <button
                                class="btn btn-sm btn-info"
                                role="button"
                                data-section="social-media"
                                data-toggle="modal"
                                data-target="#profileModal"
                                data-href="<?=$this->url('user/manage-profile', ['action' => 'social-media', 'userName' => $data->userName]) ?>">Edit</button>
                            <?php
                        endif;
                        ?>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Email</h6>
                                </div>
                                <div class="col-sm-9 text-primary">
                                <span class="text-primary"><?php echo $this->data->email; ?></span>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Phone</h6>
                                </div>
                                <div class="col-sm-9 text-primary">
                                    <?php
                                    if (isset($this->data->homePhone)) {
                                            echo $this->data->homePhone;
                                    } else {
                                        echo "Not Provided";
                                    }
                                    ?>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Mobile</h6>
                                </div>
                                <div class="col-sm-9 text-primary">
                                    <?php
                                    if (isset($this->data->mobileNumber)) {
                                        echo $this->data->mobileNumber;
                                    } else {
                                            echo "Not Provided";
                                    }
                                    ?>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Address</h6>
                                </div>
                                <div class="col-sm-9 text-primary">
                                    <?php
                                    if (isset($this->data->street)) {
                                            echo $this->data->street . '<br />' . $this->data->city . ', ' . $this->data->state . " " . $this->data->zip;
                                    } else {
                                            echo "Not Provided";
                                    }
                                    ?>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-12">
                                <?php
                                if ($this->acl()->isAllowed($this->identity()->getIdentity(), $data, 'edit')) {
                                    ?>
                                    <a class="btn btn-sm btn-info" href="<?= $this->url('user/profile', ['action' => 'edit-profile', 'userName' => $data->userName]) ?>" role="button">Edit</a>
                                        <?php
                                }
                                ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row gutters-sm">
                        <div class="col-sm-6 mb-3">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                                    <small>Web Design</small>
                                    <div class="progress mb-3" style="height: 5px">
                                        <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <small>Website Markup</small>
                                    <div class="progress mb-3" style="height: 5px">
                                        <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <small>One Page</small>
                                    <div class="progress mb-3" style="height: 5px">
                                        <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <small>Mobile Template</small>
                                    <div class="progress mb-3" style="height: 5px">
                                        <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <small>Backend API</small>
                                    <div class="progress mb-3" style="height: 5px">
                                        <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6 mb-3">
                            <div class="card h-100">
                                <div class="card-body">
                                    <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                                    <small>Web Design</small>
                                    <div class="progress mb-3" style="height: 5px">
                                        <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <small>Website Markup</small>
                                    <div class="progress mb-3" style="height: 5px">
                                        <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <small>One Page</small>
                                    <div class="progress mb-3" style="height: 5px">
                                        <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <small>Mobile Template</small>
                                    <div class="progress mb-3" style="height: 5px">
                                        <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <small>Backend API</small>
                                    <div class="progress mb-3" style="height: 5px">
                                        <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="profileModal" tabindex="-1" role="dialog" aria-labelledby="profileModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="profile-work-space" class="modal-body"></div>
            </div>
        </div>
    </div>
</div>