<!-- Checkout Start -->
<?php
    $enablePayment = $this->config()['module_settings']['payment']['enabled'];
    if ($enablePayment && $this->integrationType === 'hosted_fields') {
        $this->headScript()
        ->offsetSetFile(20, 'https://js.braintreegateway.com/web/3.91.0/js/client.min.js')
        ->offsetSetFile(21, 'https://js.braintreegateway.com/web/3.91.0/js/hosted-fields.min.js')
        ->offsetSetFile(22, 'https://js.braintreegateway.com/web/3.91.0/js/data-collector.min.js'); // I think we only need this for hosted fields...
    }
    if ($enablePayment && $this->integrationType === 'drop_in') {
       // $this->headLink()->appendStylesheet('https://assets.braintreegateway.com/web/dropin/1.35.0/css/dropin.min.css', 'text/css');
        $this->inlineScript()
        //->appendFile('https://js.braintreegateway.com/web/3.91.0/js/client.min.js', 'text/javascript')
        ->offsetSetFile(20, 'https://js.braintreegateway.com/web/dropin/1.35.0/js/dropin.min.js', 'text/javascript')
        ->offsetSetFile(21, 'https://js.braintreegateway.com/web/3.90.0/js/data-collector.min.js', 'text/javascript');

        $this->headLink()->offsetSetStylesheet(100, 'https://assets.braintreegateway.com/web/dropin/1.35.0/css/dropin.min.css');
    }

?>
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <div class="col-lg-8">
            <div class="mb-4">
                <h4 class="font-weight-semi-bold mb-4">Shipping Address</h4>
                <div class="row">
                    <div class="col-md-12 form-group">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="newaccount">
                            <label class="custom-control-label" for="newaccount">Create an account</label>
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="shipto">
                            <label class="custom-control-label" for="shipto"  data-toggle="collapse" data-target="#shipping-address">Ship to different address</label>
                        </div>
                    </div>
                </div>
            </div>
            <form id="shipping">
            <fieldset name="shipping" form="shipping">
                <div class="collapse mb-4" id="shipping-address">
                    <h4 class="font-weight-semi-bold mb-4">Shipping Address</h4>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label>First Name</label>
                            <input class="form-control" type="text" placeholder="John" form="shipping" name="firstName">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Last Name</label>
                            <input class="form-control" type="text" placeholder="Doe">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>E-mail</label>
                            <input class="form-control" type="text" placeholder="example@email.com">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Mobile No</label>
                            <input class="form-control" type="text" placeholder="+123 456 789">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Address Line 1</label>
                            <input class="form-control" type="text" placeholder="123 Street">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Address Line 2</label>
                            <input class="form-control" type="text" placeholder="123 Street">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>Country</label>
                            <select class="custom-select">
                                <option selected>United States</option>
                            </select>
                        </div>
                        <div class="col-md-6 form-group">
                            <label>City</label>
                            <input class="form-control" type="text" placeholder="New York">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>State</label>
                            <input class="form-control" type="text" placeholder="New York">
                        </div>
                        <div class="col-md-6 form-group">
                            <label>ZIP Code</label>
                            <input class="form-control" type="text" placeholder="123">
                        </div>
                    </div>
                </div>
            </fieldset>
            </form>
        </div>
        <div class="col-lg-4">
            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">Order Total</h4>
                </div>
                <div class="card-body">
                    <h5 class="font-weight-medium mb-3">Products</h5>
                    <?php
                    if (isset($this->products)) {
                        foreach ($this->products as $productGroup) {
                            echo $this->partialLoop('store/cart/partials/checkout-row', $productGroup);
                        }
                    }
                    ?>
                    <hr class="mt-0">
                    <div class="d-flex justify-content-between mb-3 pt-1">
                        <h6 class="font-weight-medium">
                            <?=$this->translate('subtotal')?>
                        </h6>
                        <h6 class="font-weight-medium">
                            <?=$this->currencyFormat($this->cart()->getSubTotal(), 'USD')?>
                        </h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">
                            <?=$this->translate('shipping')?>
                        </h6>
                        <h6 class="font-weight-medium">
                            <?=$this->currencyFormat($this->cart()->getShipping(), 'USD')?>
                        </h6>
                    </div>
                </div>
                <div class="card-footer border-secondary bg-transparent">
                    <div class="d-flex justify-content-between mt-2">
                        <h5 class="font-weight-bold">
                            <?=$this->translate('total')?>
                        </h5>
                        <h5 class="font-weight-bold">
                            <?=$this->currencyFormat($this->cart()->getTotal(), 'USD')?>
                        </h5>
                    </div>
                </div>
            </div>
            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">Payment</h4>
                </div>
                <div class="card-body">
                <?php if ($enablePayment && $this->integrationType === 'drop_in') : ?>
                    <form id="payment-form" action="/payment/braintree/confirmation" method="post">
                        <!-- dropin target div -->
                        <div id="dropin-container"></div>
                        <input type="hidden" id="nonce" name="paymentMethodNonce">
                        <input type="hidden" id="deviceData" name="deviceData">
                        <div class="text-center">
                            <button id="submit-button" class="btn btn-primary btn-lg" type="submit">Pay with <span id="card-brand">Card</span></button>
                        </div>
                    </form>
                <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Checkout End -->