<?php

declare(strict_types=1);

use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 */
$title = 'Member List';
$this->headTitle($title);
?>

<div class="jumbotron">
    <h6><?= $this->escapeHtml($title) ?></h6>
    <?php
    if ($this->acl->isAllowed($this->user, $this->user, 'user.create.new')) :
    ?>
        <span><a href="<?= $this->url('user/register', ['id' => 0]) ?>" class="btn btn-outline-info btn-sm">Add User</a></span>
    <?php
    endif;
    ?>
    <div class="card-deck">
        <?php
        foreach ($users as $listUser) :
        ?>
        <div class="card">
            <div class="card-header">
                <span class="header-text text-left float-left"><?=$listUser->firstName . '&nbsp;' . $listUser->lastName?></span>
                <div class="toolbar float-right">
                    <a class="mdi mdi-logout text-success" href=""></a>
                    <span class="mdi mdi-logout text-success"></span>
                    <span class="mdi mdi-logout text-success"></span>
                </div>
            </div>
            <div class="card-body">
                <p><?=$listUser->bio?></p>
            </div>
        </div>
        <?php
        endforeach;
        ?>
    </div>
</div>