<?php

declare(strict_types=1);

use Laminas\View\Renderer\PhpRenderer;

/**
 * @var PhpRenderer $this
 */
$title = 'Member List';
$this->headTitle($title);
?>

<div class="jumbotron">
    <h6><?= $this->escapeHtml($title) ?></h6>
    <?php
    if ($this->acl()->isAllowed($this->user, $this->user, 'register')) :
    ?>
        <span><a href="<?= $this->url('user/register', ['id' => 0]) ?>" class="btn btn-outline-info btn-sm">Add User</a></span>
    <?php
    endif;
    ?>
    <div class="card-deck">
        <?php
        foreach ($users as $listUser) :
            $user = $this->identity()->getIdentity();
            $ownerId = $listUser->getOwnerId();
        ?>
        <div class="card">
            <div class="card-header">
                <span class="header-text text-left float-left"><?=$listUser->firstName . '&nbsp;' . $listUser->lastName?></span>
                <div class="toolbar float-right">
                    <?php
                    if($this->acl()->isAllowed($this->identity()->getIdentity(), $listUser, 'delete') && $listUser->id !== '1'):
                    ?>
                        <a class="mdi mdi-delete-forever text-danger align-middle" data-toggle="tooltip" title="Delete User" href="<?= $this->url('user/account/delete', ['userName' => $listUser->userName]); ?>"></a>
                    <?php
                    endif;
                    ?>
                    <?php
                    if($this->acl()->isAllowed($this->identity()->getIdentity(), $listUser, 'edit')): ?>
                        <a class="mdi mdi-account-edit text-success align-middle" data-toggle="tooltip" title="Edit User" href="<?=$this->url('user/account/edit', ['userName' => $listUser->userName]); ?>"></a>
                    <?php
                    endif; ?>
                    <span> | </span>
                    <?php
                    if ($listUser->active) : ?>
                        <span class="mdi mdi-check-circle text-success align-middle" data-toggle="tooltip" title="Active Account"></span>
                    <?php
                    endif;
                    if ($listUser->verified) : ?>
                         <span class="mdi mdi-check-decagram text-success align-middle" data-toggle="tooltip" title="Verified Account"></span>
                    <?php
                    endif; ?>
                </div>
            </div>
            <div class="card-body">
                <div class="text-center">
                    <img class="img-fluid rounded-circle" src="/modules/user/profile/profileImages/<?=$listUser->profileImage ?? 'default-profile-picture.png';?>"/>
                </div>
                <p><?=$listUser->bio?></p>
                <span class="regdate text-info"><?=$this->translate('Registered On') . ' ' . $listUser->regDate ?? '' ?></span>
            </div>
        </div>
        <?php
        endforeach;
        ?>
    </div>
</div>