<?php

/**
 * !!!!!!!!!!!! This markup needs changed to show the shop view, with filtering options etc and the product listings !!!!!!!!!
 * phpcs:ignoreFile
 */
declare(strict_types=1);

use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
?>

<?php
if (isset($this->showHeader) && $this->showHeader) {
    echo $this->pageHeader(isset($this->headerTitle) ? $this->headerTitle : 'Title Not Found');
}
?>
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <?php
        if (isset($this->sidebar)) {
            echo $this->sidebar;
        }
        ?>
        <?php
        if ($this->products) :
        ?>
            <!-- Shop Product Start -->
            <div id="product-workspace" class="col-lg-9 col-md-12">
                <div class="row pb-3">
                    <div class="col-12 pb-1">
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <form action="">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search by name">
                                    <div class="input-group-append">
                                        <span class="input-group-text bg-transparent text-primary">
                                            <i class="fa fa-search"></i>
                                        </span>
                                    </div>
                                </div>
                            </form>
                            <div class="dropdown ml-4">
                                <button class="btn border dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">
                                            Sort by
                                        </button>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="triggerId">
                                    <a class="dropdown-item" href="#">Latest</a>
                                    <a class="dropdown-item" href="#">Popularity</a>
                                    <a class="dropdown-item" href="#">Best Rating</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php
                    if(count($this->products)) {
                        foreach ($this->products as $product) {
                            echo $this->partial('/store/partials/product-listing.phtml', $product);
                        }
                    }
                    ?>
                    <div class="col-12 pb-1">
                        <!-- pagination control renders here -->
                        <?php
                        if ($this->config('module_settings')['store']['pagination']['enabled']) {
                            echo $this->paginationControl(
                                $this->products,
                                'Sliding',
                                $this->config('module_settings')['store']['pagination']['control_partial'],
                                ['category' => $this->category, 'route' => 'store/product']
                            );
                        }
                        ?>
                        <!-- end control -->
                    </div>
                </div>
            </div>
            <!-- Shop Product End -->
        <?php
        endif;
        ?>
    </div>
</div>