
<?php

    foreach ($this->paginator as $member) :
        ?>
        <tr>
            <td>
                <img src="/modules/user/profile/profileImages/<?= $member->profileImage ?>" alt="Not found" />
            </td>
            <td> <?= $member->firstName . ' ' . $member->lastName ?> </td>
            <td> <?= $member->groupName ?> </td>
            <td> <?= $member->regDate ?> </td>
            <td> </td>
            <td>
                <div class="badge badge-outline-success">Approved</div>
            </td>
        </tr>
        <?php
    endforeach;
    ?>
