<?php

declare(strict_types=1);

use Laminas\View\Renderer\PhpRenderer;
/** @var PhpRenderer $this */
$this->headMeta()->prependName('description', $this->page->description);
$this->headTitle($this->page->label);
?>
<div class="jumbotron">
    <div class="card-deck">
        <div class="card">
            <div class="card-header">
            <?php
            if($this->acl()->isAllowed($this->identity()->getIdentity(), 'page', 'edit')) :
            ?>
            <a
            class="mdi mdi-pencil"
            data-toggle="modal"
            data-target="#editorModal"
            data-href="<?=$this->url('admin.content/manager/edit', ['title' => $this->page->title])?>"
            href="#">
            </a>
            <a
            class="delete-page mdi mdi-delete-forever text-danger"
            href="<?=$this->url('admin.content/manager/delete', ['id' => $this->page->id])?>">
            </a>
            <?php endif; ?>
                <h5><?=$this->page->label?></h5>
            </div>
            <div class="card-body">
                <?=$this->page->content;?>
            </div>
        </div>
    </div>
    <div class="modal fade" id="editorModal" tabindex="-1" role="dialog" aria-labelledby="editorModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editorModalLabel">Edit Page <?=$this->page->lagel?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="work-space" class="modal-body"></div>

            </div>
        </div>
    </div>
</div>