<?php

declare(strict_types=1);

use Laminas\View\Renderer\PhpRenderer;
/** @var PhpRenderer $this */
$this->headMeta()->prependName('keywords', $this->title . ', ' . $this->appSettings['seo']['key_words']);
$container = $this->navigation('default')->getContainer();
$page = $container->findOneBy('title', $this->title);
$this->headTitle($page->label);
$status = $page->isActive();
$this->headTitle($page->label);
?>
<div class="jumbotron">
    <div class="card-deck">
        <div class="card">
            <div class="card-header">
            <?php
            if($this->acl()->isAllowed($this->identity()->getIdentity(), 'content', 'edit')) :
            ?>
            <button
            type="button"
            class="btn-sm btn-primary mdi mdi-pencil"
            data-toggle="modal"
            data-target="#editorModal"
            data-href="<?=$this->url('admin.content/manager/edit', ['title' => $page->title])?>"></button>
            <?php endif; ?>
                <h5><?=$page->label?></h5>
            </div>
            <div class="card-body">
                <?php
                if(!empty($page)) :
                ?>
                    <?=$page->content;?>
                <?php
                endif;
                ?>
            </div>
        </div>
    </div>
    <div class="modal fade" id="editorModal" tabindex="-1" role="dialog" aria-labelledby="editorModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editorModalLabel">Edit Page <?=$page->lagel?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="work-space" class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Submit</button>
            </div>
            </div>
        </div>
    </div>
</div>