<div id="<?=$activatedUser->userName?>" class="userlist-toolbar float-right">
    <?php
    if($this->acl()->isAllowed($this->user, $activatedUser, 'delete') && $activatedUser->id !== '1'):
    ?>
        <a class="mdi mdi-delete-forever text-danger align-middle" data-toggle="tooltip" title="Delete User" href="<?= $this->url('user/account/delete', ['userName' => $activatedUser->userName]); ?>"></a>
    <?php
    endif;
    ?>
    <?php
    if($this->acl()->isAllowed($this->user, $activatedUser, 'edit') || $this->acl()->isAllowed($this->user, 'account', 'edit')): ?>
        <a class="mdi mdi-account-edit text-success align-middle" data-toggle="tooltip" title="Edit User" href="<?=$this->url('user/account/edit', ['userName' => $activatedUser->userName]); ?>"></a>
    <?php
    endif; ?>
    <span> | </span>
    <?php
    if ($activatedUser->active) { ?>
        <span class="mdi mdi-check-circle text-success align-middle" data-toggle="tooltip" title="Active Account"></span>
    <?php
    } else {
        if ($this->acl()->isAllowed($this->user, 'account', 'edit')) { ?>
            <a class="mdi mdi-check-circle text-danger align-middle activate-user"
            data-toggle="tooltip" title="Activate Account?"
            href="<?=$this->url('user/account/staff-activate', ['userName' => $activatedUser->userName]); ?>"></a>
    <?php
        }
    }
    ?>
    <?php
    if ($activatedUser->verified) : ?>
            <span class="mdi mdi-check-decagram text-success align-middle" data-toggle="tooltip" title="Verified Account"></span>
    <?php
    endif; ?>
</div>