<?php

declare(strict_types=1);

use Laminas\View\Renderer\PhpRenderer;
use User\Model\User;

/**
 * @var PhpRenderer $this
 * @var User $user
 */
?>
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
        <a class="sidebar-brand brand-logo" href="/cms/admin"><?= $this->appSettings->view->site_name ?? 'Undefined appName Setting'; ?></a>
        <a class="sidebar-brand brand-logo-mini" href="index.html"><img src="/dashboard/dark/assets/images/logo-mini.svg" alt="logo" /></a>
    </div>
    <ul class="nav">
        <li class="nav-item profile">
            <!-- open current user details section -->
            <div class="profile-desc">
                <div class="profile-pic">
                    <div class="count-indicator">
                        <img class="img-xs rounded-circle " src="/modules/user/profile/profileImages/<?= isset($this->user->profileImage) ? $this->user->profileImage : 'default-profile-picture.png'?>">
                        <span class="count bg-success"></span>
                    </div>
                    <div class="profile-name">
                        <h5 class="mb-0 font-weight-normal"></h5>
                        <span><?= $this->user->label ?? 'Unknown Role'; ?></span>
                    </div>
                </div>
                <a href="#" id="profile-dropdown" data-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
                <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
                    <a href="#" class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-settings text-primary"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1 text-small">Account settings</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-onepassword  text-info"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1 text-small">Change Password</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-calendar-today text-success"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1 text-small">To-do list</p>
                        </div>
                    </a>
                </div>
            </div>
        </li><!-- close current user section -->
        <li class="nav-item nav-category">
            <span class="nav-link">Navigation</span>
        </li>
        <?php
        foreach ($container as $page) :
            if ($page->getParent()->hasPage($page) && (count($page->pages) === 0)) :
                // top level pages with no children
                ?>
        <li class="nav-item menu-items" data-href="<?=$page->getHref()?>">
            <a class="nav-link" href="#">
                <?php
                if (isset($page->iconClass)) :
                    ?>
                    <span class="menu-icon">
                        <i class="<?=$page->iconClass?>"></i>
                    </span>
                    <?php
                endif;
                ?>
                <span class="menu-title"><?= $page->label ?></span>
            </a>
        </li>
                <?php
        // top level pages with children
            elseif ($page->getParent()->hasPage($page) && (count($page->pages) >= 1)) :
                ?>
        <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
                <?php
                if (isset($page->iconClass)) :
                    ?>
                <span class="menu-icon">
                    <i class="<?=$page->iconClass?>"></i>
                </span>
                    <?php
                endif;
                ?>
                <span class="menu-title"> <?= $page->label?> </span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-basic">
                <ul class="nav flex-column sub-menu">
                    <?php
                    $childCount = count($page->pages);
                    foreach ($page->pages as $child) :
                        ?>
                        <li class="nav-item" data-href="<?=$child->getHref()?>">
                            <a class="nav-link" href="#"><?=$child->label?></a>
                        </li>
                        <?php
                        // If there is any pages below this level we are going to render them here
                        // But do it after the pages at this level so to maintain priority
                        if (count($child->pages)) :
                            foreach ($child->pages as $grandChild) :
                                ?>
                                    <li class="nav-item" data-href="<?=$grandChild->getHref()?>">
                                        <a class="nav-link" href="#"><?=$grandChild->label?></a>
                                    </li>
                                <?php
                                continue;
                            endforeach;
                        endif;
                        ?>
                        <?php
                        continue;
                    endforeach;
                    ?>
                </ul>
            </div>
        </li>
                <?php
            endif;
        endforeach;
        ?>
    </ul>
</nav><!-- end sidebar navigation -->
