<?php

/**
 * phpcs:ignoreFile
 */
declare(strict_types=1);

use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */
$reviewsEnabled     = $this->config('module_settings')['store']['product_reviews']['enabled'];
$socialMediaEnabled = $this->config('module_settings')['store']['social_media']['enabled'];
?>
<!-- Page Header Start -->
<?=$this->pageHeader($this->product->label)?>
<!-- Page Header End -->
<!-- Shop Detail Start -->
<div class="container-fluid py-5">
    <div class="row px-xl-5">
        <div class="col-lg-5 pb-5">
            <div id="product-carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner border">
                    <?php
                    if (isset($this->images)) :
                        $i = 0;
                        foreach ($this->images as $image) :
                    ?>
                    <div class="carousel-item <?=$i === 0 ? 'active' : ''?>">
                        <img class="w-100 h-100" src="/modules/store/product/images/<?=$image['fileName']?>" alt="Image">
                    </div>
                    <?php
                        $i++;
                        endforeach;
                    endif;
                    ?>
                </div>
                <a class="carousel-control-prev" href="#product-carousel" data-slide="prev">
                    <i class="mdi mdi-arrow-left-thick text-dark"></i>
                </a>
                <a class="carousel-control-next" href="#product-carousel" data-slide="next">
                    <i class="mdi mdi-arrow-right-thick text-dark"></i>
                </a>
            </div>
        </div>
        <div class="col-lg-7 pb-5">
            <h3 class="font-weight-semi-bold"><?=$this->product->label?></h3>
        <?php if ($reviewsEnabled) : ?>
            <div class="d-flex mb-3">
                <div class="text-primary mr-2">
                    <small class="fas fa-star"></small>
                    <small class="fas fa-star"></small>
                    <small class="fas fa-star"></small>
                    <small class="fas fa-star-half-alt"></small>
                    <small class="far fa-star"></small>
                </div>
                <small class="pt-1">(50 Reviews)</small>
            </div>
        <?php endif; ?>
            <h3 class="font-weight-semi-bold mb-4">$<?=$this->product->cost?></h3>
            <form id="add-product" enctype="multipart/form-data" method="post" action="<?=$this->url('store/cart', ['action' => 'add-item'])?>">
                <?php
                foreach ($this->options as $optionGroup => $options) :
                ?>
                <div class="d-flex mb-3">
                    <p class="text-dark font-weight-medium mb-0 mr-3"><?=$optionGroup?>:</p>
                        <?php
                        $i = 0;
                        foreach ($options as $column => $option) : ?>
                            <div class="custom-control custom-radio custom-control-inline">
                                <input
                                type="radio"
                                class="custom-control-input"
                                id="<?=$option['option'] . '-' . $i?>"
                                name="<?=$optionGroup?>"
                                value="<?=$option['option']?>">
                                <label
                                class="custom-control-label"
                                for="<?=$option['option'] . '-' . $i?>">
                                    <?=$option['option']?><?=$option['cost'] !== null ? ' $' .$option['cost'] : ''?>
                                </label>
                            </div>
                        <?php
                        $i++;
                        endforeach; ?>
                </div>
                <?php
                endforeach;
                ?>
                <input type="hidden" name="id" value="<?=$this->product->id?>">
                <input type="hidden" name="label" value="<?=$this->product->label?>">
                <input type="hidden" name="weight" value="<?=$this->product->weight?>">
                <input type="hidden" name="cost" value="<?=$this->product->cost?>">
                <input type="hidden" name="onSale" value="<?=$this->product->onSale?>">
                <input type="hidden" name="sku" value="<?=$this->product->sku?>">
                <input type="hidden" name="image" value="<?=$this->images[0]['fileName']?>">
                <div class="d-flex align-items-center mb-4 pt-2">
                    <div class="input-group quantity mr-3" style="width: 130px;">
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-primary btn-minus" >
                            <i class="mdi mdi-minus"></i>
                            </button>
                        </div>
                        <input type="text" class="form-control bg-secondary text-center" name="quantity" value="1">
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-primary btn-plus">
                                <i class="mdi mdi-plus"></i>
                            </button>
                        </div>
                    </div>
                    <button type="button" class="add-item btn btn-primary px-3"><i class="mdi mdi-cart mr-1"></i>Add To Cart</button>
                </div>
            </form>
        <?php if ($socialMediaEnabled) :?>
            <div class="d-flex pt-2">
                <p class="text-dark font-weight-medium mb-0 mr-2">Share on:</p>
                <div class="d-inline-flex">
                    <a class="text-dark px-2" href="">
                        <i class="mdi mdi-facebook"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="mdi mdi-twitter"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="mdi mdi-linkedin"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="mdi mdi-pinterest"></i>
                    </a>
                </div>
            </div>
        <?php endif; ?>
        </div>
    </div>
    <div class="row px-xl-5">
        <div class="col">
            <div class="nav nav-tabs justify-content-center border-secondary mb-4">
                <a class="nav-item nav-link active" data-toggle="tab" href="#tab-pane-1">Description</a>
            <?php if ($reviewsEnabled) : ?>
                <a class="nav-item nav-link" data-toggle="tab" href="#tab-pane-3">Reviews (0)</a>
            <?php endif; ?>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="tab-pane-1">
                    <h4 class="mb-3">Product Description</h4>
                    <p><?=$this->product->description?></p>
                </div>
                <div class="tab-pane fade" id="tab-pane-3">
                    <div class="row">
                        <div class="col-md-6">
                            <h4 class="mb-4">1 review for "<?=$this->product->label?>"</h4>
                            <div class="media mb-4">
                                <img src="img/user.jpg" alt="Image" class="img-fluid mr-3 mt-1" style="width: 45px;">
                                <div class="media-body">
                                    <h6>John Doe<small> - <i>01 Jan 2045</i></small></h6>
                                    <div class="text-primary mb-2">
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star-half-alt"></i>
                                        <i class="far fa-star"></i>
                                    </div>
                                    <p>Diam amet duo labore stet elitr ea clita ipsum, tempor labore accusam ipsum et no at. Kasd diam tempor rebum magna dolores sed sed eirmod ipsum.</p>
                                </div>
                            </div>
                        </div>
                    <?php if ($reviewsEnabled) : ?>
                        <div class="col-md-6">
                            <h4 class="mb-4">Leave a review</h4>
                            <small>Your email address will not be published. Required fields are marked *</small>
                            <div class="d-flex my-3">
                                <p class="mb-0 mr-2">Your Rating * :</p>
                                <!-- product rating -->
                                <?=$this->productRating(4, 'mdi-star', 'text-primary')?>
                                <!-- product rating -->
                            </div>
                            <form>
                                <div class="form-group">
                                    <label for="message">Your Review *</label>
                                    <textarea id="message" cols="30" rows="5" class="form-control"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="name">Your Name *</label>
                                    <input type="text" class="form-control" id="name">
                                </div>
                                <div class="form-group">
                                    <label for="email">Your Email *</label>
                                    <input type="email" class="form-control" id="email">
                                </div>
                                <div class="form-group mb-0">
                                    <input type="submit" value="Leave Your Review" class="btn btn-primary px-3">
                                </div>
                            </form>
                        </div>
                    <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Shop Detail End -->