<?php
use Laminas\Filter\DateTimeFormatter;
$filter = new DateTimeFormatter(['format' => 'm-j-Y \a\t g:i:s A']);
$allowDelete = $this->acl()->isAllowed($this->identity()->getIdentity(), $resourceId, 'delete');
?>
<div class="log-message alert alert-<?=$this->mapPriority($priority)?><?=$allowDelete ? ' alert-dismissible fade show' : '';?>" data-id="<?= $logId?>">
    <?php
    if ($allowDelete) :
    ?>
        <a href="#" data-href="<?=$this->url('admin/logs/delete', ['id' => $logId])?>" type="button" class="close delete-log" data-dismiss="alert" aria-label="Close">
            <span class="mdi mdi-delete-forever" aria-hidden="true"></span>
        </a>
    <?php
    endif; ?>

    <span class="log-message-detail">First Name: <?= $extra_firstName?></span>
    <span class="log-message-detail">Last Name: <?= $extra_lastName?></span>
    <span class="log-message-detail">UserName: <?= $extra_userName?></span>
    <span class="log-message-detail">MemberGroup: <?= $this->translate($extra_role)?></span>
    <span class="log-message-detail">Occurred On: <?= $filter->filter(DateTime::createFromFormat('m-d-Y H:i:s', $timeStamp))?></span>
    <div class="log-message">
        <span class="log-message-header">
            Message:
        </span>
        <p class="log-message-text">
            <?= $this->translate($message) ?>
        </p>
    </div>
</div>