<?php
if (! $this->error) :
?>
    <div class="row justify-content-center" style="margin-bottom:1em;">
    <div class="btn-group" role="group" aria-label="Log Control">
        <button type="button" class="btn btn-secondary">Activity Log</button>
        <button type="button" class="btn btn-secondary">Error Log</button>
    </div>
    </div>
<div class="log-overview"><!-- open log-overview -->
    <div id="log-workspace" class="container">
        <?php
        foreach ($this->data as $log) :
            echo $this->partial('app/partials/log-message.phtml', $log);
        endforeach;
        ?>
    </div>
</div><!-- close log-overview -->
<?php
endif;
?>