<!-- Cart Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <div id="cart-checkout-workspace" class="col-lg-8 table-responsive mb-5">
            <table class="table table-bordered text-center mb-0">
                <thead class="bg-secondary text-dark">
                    <tr>
                        <th><?=$this->translate('products')?></th>
                        <th><?=$this->translate('options')?></th>
                        <th><?=$this->translate('price')?></th>
                        <th><?=$this->translate('remove')?></th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                <?php
                if (isset($this->products)):
                    foreach ($this->products as $productGroup):
                ?>
                    <?=$this->partialLoop('store/cart/partials/cart-row', $productGroup)?>
                <?php
                    endforeach;
                endif; ?>
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
        <?php if ($this->config('module_settings')['store']['order']['enable_coupons']): ?>
            <form class="mb-5" action="">
                <div class="input-group">
                    <input type="text" class="form-control p-4" placeholder="<?=$this->translate('coupon_placeholder')?>">
                    <div class="input-group-append">
                        <button class="btn btn-primary">
                            <?=$this->translate('coupon_control_label')?>
                        </button>
                    </div>
                </div>
            </form>
        <?php endif; ?>
            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">
                        <?=$this->translate('order_summary')?>
                    </h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between mb-3 pt-1">
                        <h6 class="font-weight-medium">
                            <?=$this->translate('subtotal')?>
                        </h6>
                        <h6 id="cart-subtotal" class="font-weight-medium">
                            <?=$this->currencyFormat($this->cart()->getSubTotal(), 'USD')?>
                        </h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">
                           <?=$this->translate('shipping')?>
                        </h6>
                        <h6 id="cart-shipping" class="font-weight-medium">
                            <?=$this->currencyFormat($this->cart()->getShipping(), 'USD')?>
                        </h6>
                    </div>
                </div>
                <div class="card-footer border-secondary bg-transparent">
                    <div class="d-flex justify-content-between mt-2">
                        <h5 class="font-weight-bold">
                            <?=$this->translate('total')?>
                        </h5>
                        <h5 id="cart-total" class="font-weight-bold">
                            <?=$this->currencyFormat($this->cart()->getTotal(), 'USD')?>
                        </h5>
                    </div>
                    <?php
                    if (isset($this->products)) : ?>
                    <button class="empty-cart btn btn-primary btn-sm">
                        <?=$this->translate('empty_cart')?>
                    </button>
                    <?php
                    endif; ?>
                    <button class="btn btn-block btn-primary my-3 py-3">
                        <?=$this->translate('go_to_checkout')?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->